export const jewelryOptions = {
  Budget: ['less than 2k', '2-5k', 'over 5k'],
  Gender: ['Male', 'Female', 'unisex'],
  Style: ['African Jewelry','Antique Jewelry', 'Art Deco', 'Art Nouveau', 'Artistic', 'Asymmetrical', 'Avant-Garde', 'Baroque', 'Beaded Jewelry', 'Black Jewellery', 'Bohemian', 'Byzantine', 'Celestial Jewelry', 'Contemporary', 'Eco-Friendly Jewelry', 'Edwardian', 'Enamel Jewelry', 'Ethnic', 'Fashion','Floral inspired','Geode Jewelry', 'Geometric', 'Gothic', 'Haute Joaillerie', 'Heirloom Jewelry', 'Industrial', 'Kawaii Jewelry', 'Layered Jewelry','Mermaid inspired', 'Maximalist', 'Minimalist', 'Modern', 'Nature-Inspired Jewelry', 'Organic', 'Pearlcore', 'Punk-Inspired', 'Retro', 'Retro Futurism', 'Rococo', 'Sculptural Jewelry', 'Stackable Jewelry', 'Statement', 'Steampunk', 'Sustainable', 'Tribal', 'Victorian', 'Vintage', 'Personalized Jewelry', 'Custom'],
  Male_Jewellery: ['Signet Ring', 'Band Ring', 'Cuff Ring', 'Gemstone Ring', 'Spinner Ring', 'Chain Necklace', 'Pendant Necklace', 'Dog Tag Necklace', 'ID Tag Necklace', 'Minimal Necklace', 'Chain Bracelet', 'Beaded Bracelet', 'Cuff Bracelet', 'Wrap Bracelet', 'Contrast Chain Bracelet', 'Stud Earrings', 'Hoop Earrings', 'Drop Earrings', 'Cufflinks', 'Tie Clip', 'Money Clip', 'Decorative Pin', 'Vintage Brooche', 'ID Bracelet'],
  Female_Jewellery: ['Engagement Ring', 'Wedding Ring', 'Statement Ring', 'Promise Ring', 'Cocktail Ring', 'Stackable Rings', 'Necklace', 'Pendant Necklace', 'Statement Necklace', 'Pearl Necklace', 'Choker Necklace', 'Tennis Necklace', 'Heart Motif Necklace', 'Chunky Necklace', 'Domed-Shaped Necklace', 'Initial Necklace', 'Bangles', 'Cuff Bracelet', 'Charm Bracelet', 'Tennis Bracelet', 'Beaded Bracelet', 'Stud Earrings', 'Hoop Earrings', 'Dangle Earrings', 'Decorative Pin', 'Vintage Brooche', 'Pearl Earrings', 'Chandelier Earrings', 'Nose Stud','Nose Ring', 'Anklet Bracelet'],
  unisex_Jewellery: ['Band Ring', 'Minimal Necklace', 'Chain Bracelet', 'Stud Earrings', 'Hoop Earrings', 'Cuff Bracelet', 'Beaded Bracelet'],
  Base_Metal: ['Gold', 'Rose Gold', 'White Gold', 'Platinum', 'Tricolour Gold', 'Silver', 'Palladium'],
  Kwt: ['9K', '14K', '18K', '22K'],
  Ring_Style: ['Plain Band', 'Solitaire', 'Solitaire with Halo', 'Trilogy', 'Gem on Band', 'Eternity', 'Fashion', 'Three Stone', 'Diamond Wedding Band', 'Signet', 'Cocktail Rings', 'Stackable Rings', 'Birthstone Rings', 'Promise Rings', 'Vintage Rings'],
  Ring_Sizes_UK: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
  Ring_Sizes_US: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14'],
  Band_width: ['Thin', 'Medium', 'Thick'],
  Gemstone: ['Diamond', 'Ruby', 'Sapphire', 'Emerald', 'Amethyst', 'Topaz', 'Aquamarine', 'Opal', 'Garnet', 'Pearl', 'Peridot', 'Turquoise', 'Citrine', 'Tanzanite', 'Morganite', 'Alexandrite', 'Tourmaline', 'Spinel', 'Zircon', 'Onyx', 'Moonstone', 'Quartz', 'LapisLazuli', 'Jade', 'Amber', 'Coral', 'Chrysoprase', 'Malachite', 'Bloodstone'],
  Gemstone_Source: ['Natural', 'Labgrown', 'Ethically sourced'],
  Gemstone_colour: {
    Diamond: ['Colourless', 'Near Colourless', 'Slight Colour', 'Yellow', 'Blue', 'Pink', 'Green', 'Red', 'Brown', 'Champagne', 'Cognac', 'Coffee'],
    Ruby: ['Vivid Red', 'Pigeon Blood Red', 'Pinkish Red'],
    Sapphire: ['Blue', 'Cornflower Blue', 'Padparadscha', 'Yellow', 'Green', 'Purple', 'Pink'],
    Emerald: ['Vivid Green', 'Bluish Green'],
    Amethyst: ['Deep Purple', 'Light Purple', 'Lavender'],
    Topaz: ['Imperial Topaz', 'Blue', 'Colorless', 'Yellow', 'Pink'],
    Aquamarine: ['Light Blue', 'Greenish Blue'],
    Opal: ['White', 'Black', 'Fire'],
    Garnet: ['Red', 'Green', 'Orange', 'Purple'],
    Pearl: ['White', 'Cream', 'Black', 'Pink', 'Silver', 'Gold'],
    Peridot: ['Yellowish Green', 'Olive Green'],
    Turquoise: ['Sky Blue', 'Greenish Blue'],
    Citrine: ['Yellow', 'Madeira'],
    Tanzanite: ['Blue', 'Violet'],
    Morganite: ['Pink', 'Peach'],
    Alexandrite: ['Color-changing'],
    Tourmaline: ['Pink', 'Green', 'Blue', 'Watermelon'],
    Spinel: ['Red', 'Pink', 'Blue', 'Violet'],
    Zircon: ['Blue', 'Red', 'Green', 'Yellow', 'Brown', 'Colorless'],
    Onyx: ['Black', 'Banded'],
    Moonstone: ['Colorless with Blue Sheen', 'Peach'],
    Quartz: ['Clear', 'Rose', 'Smoky', 'Amethyst'],
    LapisLazuli: ['Deep Blue with Golden Flecks'],
    Jade: ['Green', 'White', 'Lavender', 'Yellow'],
    Amber: ['Yellow', 'Orange', 'Brown'],
    Coral: ['Red', 'Pink', 'White'],
    Chrysoprase: ['Apple Green'],
    Malachite: ['Green with Banded Patterns'],
    Bloodstone: ['Dark Green with Red Spots']
  },
  
  Gem_Shapes: {
    Diamond: ['Round', 'Princess', 'Emerald', 'Asscher', 'Marquise', 'Oval', 'Radiant', 'Pear', 'Heart', 'Cushion'],
    Ruby: ['Round', 'Oval', 'Cushion', 'Pear', 'Emerald', 'Marquise'],
    Sapphire: ['Round', 'Oval', 'Cushion', 'Pear', 'Emerald', 'Marquise'],
    Emerald: ['Round', 'Oval', 'Cushion', 'Pear', 'Emerald', 'Marquise'],
    Amethyst: ['Round', 'Oval', 'Cushion', 'Pear'],
    Topaz: ['Round', 'Oval', 'Cushion', 'Pear'],
    Aquamarine: ['Round', 'Oval', 'Cushion', 'Pear'],
    Opal: ['Round', 'Oval', 'Cushion'],
    Garnet: ['Round', 'Oval', 'Cushion', 'Pear'],
    Pearl: ['Round'],
    Peridot: ['Round', 'Oval', 'Cushion'],
    Turquoise: ['Round', 'Oval', 'Cushion'],
    Citrine: ['Round', 'Oval', 'Cushion', 'Pear'],
    Tanzanite: ['Round', 'Oval', 'Cushion', 'Pear'],
    Morganite: ['Round', 'Oval', 'Cushion', 'Pear'],
    Alexandrite: ['Round', 'Oval', 'Cushion'],
    Tourmaline: ['Round', 'Oval', 'Cushion', 'Pear'],
    Spinel: ['Round', 'Oval', 'Cushion'],
    Zircon: ['Round', 'Oval', 'Cushion', 'Pear'],
    Onyx: ['Round', 'Oval', 'Cushion'],
    Moonstone: ['Round', 'Oval', 'Cushion'],
    Quartz: ['Round', 'Oval', 'Cushion', 'Pear'],
    LapisLazuli: ['Round', 'Oval', 'Cushion'],
    Jade: ['Round', 'Oval', 'Cushion'],
    Amber: ['Round', 'Oval', 'Cushion'],
    Coral: ['Round', 'Oval', 'Cushion'],
    Chrysoprase: ['Round', 'Oval', 'Cushion'],
    Malachite: ['Round', 'Oval', 'Cushion'],
    Bloodstone: ['Round', 'Oval', 'Cushion']
  },
  Carat_Weight: [
    '0.30-4.3mm',
    '0.40-4.7mm',
    '0.50-5.1mm',
    '0.60-5.4mm',
    '0.70-5.7mm',
    '0.80-5.9mm',
    '0.90-6.1mm',
    '1.00-6.5mm',
    '1.20-6.8mm',
    '1.40-7.1mm',
    '1.60-7.4mm',
    '1.80-7.7mm',
    '2.00-7.9mm',
    '2.20-8.2mm',
    '2.40-8.4mm',
    '2.60-8.6mm',
    '2.80-8.8mm',
    '3.00-9.0mm',
    '3.20-9.2mm',
    '3.40-9.3mm',
    '3.50-9.4mm'
  ],
  Clarity: ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2'],
  Cut: ['Excellent', 'Very Good', 'Good', 'Fair'],
  Prompt_Strength: [2,3,4,5,6,7,8,9,10],
  Similarity_Strength: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
  Necklace_Length: ['14 inches (35.56 cm)', '16 inches (40.64 cm)', '18 inches (45.72 cm)', '20 inches (50.8 cm)', '22 inches (55.88 cm)', '24 inches (60.96 cm)', '30 inches (76.2 cm)', '36 inches (91.44 cm)'],
  Bracelet_Length: ['6 inches (15.24 cm)', '6.5 inches (16.51 cm)', '7 inches (17.78 cm)', '7.5 inches (19.05 cm)', '8 inches (20.32 cm)', '8.5 inches (21.59 cm)'],
  Secondary_Gemstone: ['No','Diamond', 'Ruby', 'Sapphire', 'Emerald', 'Amethyst', 'Topaz', 'Aquamarine', 'Opal', 'Garnet', 'Pearl', 'Peridot', 'Turquoise', 'Citrine', 'Tanzanite', 'Morganite', 'Alexandrite', 'Tourmaline', 'Spinel', 'Zircon', 'Onyx', 'Moonstone', 'Quartz', 'LapisLazuli', 'Jade', 'Amber', 'Coral', 'Chrysoprase', 'Malachite', 'Bloodstone'],
  Earring_Fastening_Types: ['Push-Back', 'Screw-Back', 'Lever-Back', 'Clip-On', 'French Wire', 'Fish Hook', 'Hinged Hoop', 'Latch-Back', 'Omega Back', 'Threader', 'Huggie', 'Magnetic'],
  Bracelet_Clasp_Types: ['Lobster Clasp', 'Spring-Ring Clasp', 'Toggle Clasp', 'Magnetic Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Buckle Clasp', 'Fold-Over Clasp', 'Hook-and-Eye Clasp', 'Button Clasp', 'Screw Clasp', 'Barrel Clasp'],
  Ring_Band_Style: ['Classic', 'Infinity', 'Twisted', 'Hammered', 'Beveled', 'Comfort Fit', 'Split Shank', 'Pavé', 'Channel Set', 'Milgrain', 'Filigree', 'Stackable', 'Wide Band', 'Tapered'],
  Ring_Setting: ['Prong', 'Bezel', 'Tension', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Gypsy', 'Basket', 'Invisible', 'Three-Stone'],
  Necklace_Chain_Style: ['Cable Chain', 'Rope Chain', 'Box Chain', 'Snake Chain', 'Figaro Chain', 'Curb Chain', 'Singapore Chain', 'Bead Chain', 'Byzantine Chain', 'Popcorn Chain', 'Herringbone Chain', 'Wheat Chain'],
  Bracelet_Chain_Style: ['Cable Chain', 'Rope Chain', 'Box Chain', 'Snake Chain', 'Figaro Chain', 'Curb Chain', 'Singapore Chain', 'Bead Chain', 'Byzantine Chain', 'Popcorn Chain', 'Herringbone Chain', 'Wheat Chain'],
  Brooch_Fastening_Types: ['Pin Back', 'C-Clasp', 'T-Bar', 'Safety Catch', 'Locking Clasp', 'Magnetic Back', 'Slide Lock', 'Screw Back', 'Spring-Loaded Clasp', 'Latch Back'],
  Gem_Settings: {
    Diamond: ['Prong', 'Bezel', 'Tension', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Gypsy', 'Basket', 'Invisible', 'Three-Stone'],
    Ruby: ['Prong', 'Bezel', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Sapphire: ['Prong', 'Bezel', 'Tension', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Emerald: ['Bezel', 'Channel', 'Halo', 'Cathedral', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Amethyst: ['Prong', 'Bezel', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Topaz: ['Prong', 'Bezel', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Aquamarine: ['Prong', 'Bezel', 'Channel', 'Halo', 'Cathedral', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Opal: ['Bezel', 'Halo', 'Bar', 'Cluster', 'Basket'],
    Garnet: ['Prong', 'Bezel', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Pearl: ['Bezel', 'Bar', 'Cluster', 'Basket'],
    Peridot: ['Prong', 'Bezel', 'Channel', 'Halo', 'Cathedral', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Turquoise: ['Bezel', 'Channel', 'Halo', 'Bar', 'Cluster', 'Basket'],
    Citrine: ['Prong', 'Bezel', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Tanzanite: ['Prong', 'Bezel', 'Channel', 'Halo', 'Cathedral', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Morganite: ['Prong', 'Bezel', 'Channel', 'Halo', 'Cathedral', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Alexandrite: ['Prong', 'Bezel', 'Channel', 'Halo', 'Cathedral', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Tourmaline: ['Prong', 'Bezel', 'Channel', 'Halo', 'Cathedral', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Spinel: ['Prong', 'Bezel', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Zircon: ['Prong', 'Bezel', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    Onyx: ['Bezel', 'Channel', 'Bar', 'Cluster', 'Basket'],
    Moonstone: ['Bezel', 'Channel', 'Halo', 'Bar', 'Cluster', 'Basket'],
    Quartz: ['Prong', 'Bezel', 'Channel', 'Pavé', 'Halo', 'Cathedral', 'Flush', 'Bar', 'Cluster', 'Basket', 'Three-Stone'],
    LapisLazuli: ['Bezel', 'Channel', 'Bar', 'Cluster', 'Basket'],
    Jade: ['Bezel', 'Channel', 'Bar', 'Cluster', 'Basket'],
    Amber: ['Bezel', 'Bar', 'Cluster', 'Basket'],
    Coral: ['Bezel', 'Bar', 'Cluster', 'Basket'],
    Chrysoprase: ['Bezel', 'Channel', 'Bar', 'Cluster', 'Basket'],
    Malachite: ['Bezel', 'Channel', 'Bar', 'Cluster', 'Basket'],
    Bloodstone: ['Bezel', 'Channel', 'Bar', 'Cluster', 'Basket']
  },
  Necklace_Clasp: {
    'Cable Chain': ['Lobster Clasp', 'Spring-Ring Clasp', 'Toggle Clasp', 'Magnetic Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Fish Hook Clasp', 'Screw Clasp', 'Pearl Safety Clasp'],
    'Rope Chain': ['Lobster Clasp', 'Toggle Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Screw Clasp'],
    'Box Chain': ['Lobster Clasp', 'Spring-Ring Clasp', 'Magnetic Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Snake Chain': ['Lobster Clasp', 'Spring-Ring Clasp', 'Magnetic Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Figaro Chain': ['Lobster Clasp', 'Toggle Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Screw Clasp'],
    'Curb Chain': ['Lobster Clasp', 'Toggle Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Screw Clasp'],
    'Singapore Chain': ['Lobster Clasp', 'Spring-Ring Clasp', 'Magnetic Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Bead Chain': ['Lobster Clasp', 'Spring-Ring Clasp', 'Magnetic Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Fish Hook Clasp'],
    'Byzantine Chain': ['Lobster Clasp', 'Toggle Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Screw Clasp'],
    'Popcorn Chain': ['Lobster Clasp', 'Spring-Ring Clasp', 'Magnetic Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Herringbone Chain': ['Lobster Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Wheat Chain': ['Lobster Clasp', 'Toggle Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Screw Clasp'],
    'Anchor Chain': ['Lobster Clasp', 'Toggle Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Screw Clasp'],
    'Rolo Chain': ['Lobster Clasp', 'Spring-Ring Clasp', 'Toggle Clasp', 'Magnetic Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Venetian Chain': ['Lobster Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'San Marco Chain': ['Lobster Clasp', 'Toggle Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Omega Chain': ['Lobster Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Foxtail Chain': ['Lobster Clasp', 'Toggle Clasp', 'Box Clasp', 'Hook-and-Eye Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp'],
    'Ball Chain': ['Lobster Clasp', 'Spring-Ring Clasp', 'Magnetic Clasp', 'Box Clasp', 'Slide Lock Clasp', 'Barrel Clasp', 'Push Button Clasp', 'Fish Hook Clasp']
  },
};
